generator: admingenerator.generator.propel
params:
    model: C33s\SimpleGalleryBundle\Model\GalleryItem
    namespace_prefix: C33s
    concurrency_lock: ~
    bundle_name: SimpleGalleryBundle
    pk_requirement: ~
    fields:
        id:
            formType:   hidden
        SortableRank:
            formType:   hidden
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
#    list:
#        params:
#            title: List for SimpleGalleryBundle
#            display: ~
#            actions:
#                new: ~
#            object_actions:
#                edit: ~
#                delete: ~
#    filters:
#        params:
#            display: ~
#    new:
#        params:
#            title: New object for SimpleGalleryBundle
#            display: ~
#            actions:
#                save: ~
#                list: ~
    edit:
        params:
            title:      ""
            display:
                - id
                - Title
                - Description
                - IsListed
                - SortableRank
            actions: []
#    show:
#        params:
#            title: "You're viewing the object \"%object%\"|{ %object%: GalleryItem.title }|"
#            display: ~
#            actions:
#                list: ~
#                new: ~
#    actions:
#        params:
#            object_actions:
#                delete: ~
#            batch_actions:
#                delete: ~
