parameters:
    c33s_gallery.twig.extension.class: C33s\SimpleGalleryBundle\Twig\Extension\GalleryExtension

services:
    c33s_gallery.twig.extension:
        class: %c33s_gallery.twig.extension.class%
#        arguments: [@service_id, "plain_value", %parameter%]
        tags:
            - { name: twig.extension }
